name: melos_dependency_graph
description: A powerful CLI tool for analyzing and visualizing dependency graphs in Melos-managed Dart/Flutter monorepos with topological sorting and cycle detection.

version: 1.0.0

repository: https://github.com/carlosfiori/melos_dependency_graph
issue_tracker: https://github.com/carlosfiori/melos_dependency_graph/issues

environment:
  sdk: ^3.5.0

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.0
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.4.12
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^9.0.0

executables:
  melos_dependency_graph:
